"""text to message

Revision ID: c7be09b28bbc
Revises: 720bd203fd68
Create Date: 2025-02-11 06:06:40.652789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7be09b28bbc'
down_revision: Union[str, None] = '720bd203fd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message', sa.String(), nullable=False))
    op.drop_column('message', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('message', 'message')
    # ### end Alembic commands ###
